clear
load('temp_try')

z_all_data = z_all_data(:,1000);
z_all_blind = z_all_data;
TR_ID    =         unique(z_all_flag.Node1_ID(z_all_flag.Meas_Type == 2));
Load_IDs = setdiff(unique(z_all_flag.Node1_ID(z_all_flag.Meas_Type == 1)), TR_ID);

z_all_blind(z_all_flag.Node1_ID ~= TR_ID & z_all_flag.Meas_Type == 3) = 0;
z_all_blind(z_all_flag.Node1_ID ~= TR_ID & z_all_flag.Meas_Type == 4) = 0;
TR_P = [...
    z_all_data(z_all_flag.Node1_ID == TR_ID & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == 1);...
    z_all_data(z_all_flag.Node1_ID == TR_ID & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == 2);...
    z_all_data(z_all_flag.Node1_ID == TR_ID & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == 3) ...
    ];
TR_Q = [...
    z_all_data(z_all_flag.Node1_ID == TR_ID & z_all_flag.Meas_Type == 4 & z_all_flag.Phase == 1);...
    z_all_data(z_all_flag.Node1_ID == TR_ID & z_all_flag.Meas_Type == 4 & z_all_flag.Phase == 2);...
    z_all_data(z_all_flag.Node1_ID == TR_ID & z_all_flag.Meas_Type == 4 & z_all_flag.Phase == 3) ...
    ];

z_all_flag.Sigma(...
    ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == 1 | ...
    ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == 2 | ...
    ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == 3 | ...
    ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 4 & z_all_flag.Phase == 1 | ...
    ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 4 & z_all_flag.Phase == 2 | ...
    ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 4 & z_all_flag.Phase == 3   ...
    ) = 10;

z_all_blind(ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == 1) = - TR_P(1) / numel(Load_IDs);
z_all_blind(ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == 2) = - TR_P(2) / numel(Load_IDs);
z_all_blind(ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == 3) = - TR_P(3) / numel(Load_IDs);

z_all_blind(ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 4 & z_all_flag.Phase == 1) = - TR_Q(1) / numel(Load_IDs);
z_all_blind(ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 4 & z_all_flag.Phase == 2) = - TR_Q(2) / numel(Load_IDs);
z_all_blind(ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 4 & z_all_flag.Phase == 3) = - TR_Q(3) / numel(Load_IDs);


for k = 1 : 100
    
    [x_hat, z_hat, z_hat_full, Optional] = TaylorSE_AMA(z_all_blind, z_all_flag, LineInfo, Inputs_SE);
    
    for k_Phase = 1 : 3
        diff_U = ...
            z_hat      (ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 1 & z_all_flag.Phase == k_Phase) - ...
            z_all_blind(ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 1 & z_all_flag.Phase == k_Phase);
        adjust_P = diff_U + 1;
        % sum(adjust_P)
        z_all_blind(ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == k_Phase) = ...
            z_all_blind(ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == k_Phase) .* adjust_P;
        z_all_blind(ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == k_Phase) = ...
            z_all_blind(ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == k_Phase) * - TR_P(k_Phase)/ ...
            sum(z_all_blind(ismember(z_all_flag.Node1_ID,Load_IDs) & z_all_flag.Meas_Type == 3 & z_all_flag.Phase == k_Phase));
    end
end
